# Generated by Django 4.1.7 on 2023-05-11 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sala", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariossala",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios_sala_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="creador_username",
            field=models.ForeignKey(
                db_column="creador_username",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creador_sala",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="usuariossala",
            constraint=models.UniqueConstraint(
                fields=("nombre_sala", "username"), name="usuario_sala_pk"
            ),
        ),
    ]
