# Generated by Django 4.1.7 on 2023-03-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('respuesta_correcta', models.CharField(max_length=500)),
                ('respuesta_incorrecta1', models.CharField(max_length=500)),
                ('respuesta_incorrecta2', models.CharField(max_length=500)),
                ('respuesta_incorrecta3', models.CharField(max_length=500)),
            ],
        ),
    ]
