# Generated by Django 4.1.7 on 2023-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivial_sesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
