# Generated by Django 4.1.7 on 2023-03-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivial_sesion', '0002_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pregunta',
            table='Pregunta',
        ),
    ]
