# Generated by Django 4.1.7 on 2023-04-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Casilla_Tematica",
            fields=[
                ("casilla", models.IntegerField(primary_key=True, serialize=False)),
                ("tematica", models.CharField(max_length=50)),
                ("quesito", models.BooleanField()),
            ],
            options={
                "db_table": "Casilla_Tematica",
            },
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("terminada", models.BooleanField(default=False)),
                ("orden_jugadores", models.CharField(max_length=100)),
                ("turno_actual", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Partida",
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "enunciado",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("r1", models.CharField(blank=True, max_length=200)),
                ("r2", models.CharField(blank=True, max_length=200)),
                ("r3", models.CharField(blank=True, max_length=200)),
                ("r4", models.CharField(blank=True, max_length=200)),
                ("rc", models.IntegerField()),
                ("categoria", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Pregunta",
            },
        ),
        migrations.CreateModel(
            name="Tablero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tirada_dado", models.IntegerField()),
                (
                    "casilla_actual",
                    models.ForeignKey(
                        db_column="casilla_actual",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tablero_ac",
                        to="partida.casilla_tematica",
                    ),
                ),
                (
                    "casilla_nueva",
                    models.ForeignKey(
                        db_column="casilla_nueva",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tablero_nu",
                        to="partida.casilla_tematica",
                    ),
                ),
            ],
            options={
                "db_table": "Tablero",
            },
        ),
        migrations.CreateModel(
            name="Juega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posicion", models.IntegerField(default=72)),
                ("q_historia", models.BooleanField(default=False)),
                ("q_arte", models.BooleanField(default=False)),
                ("q_deporte", models.BooleanField(default=False)),
                ("q_ciencia", models.BooleanField(default=False)),
                ("q_entretenimiento", models.BooleanField(default=False)),
                ("q_geografia", models.BooleanField(default=False)),
                (
                    "id_partida",
                    models.ForeignKey(
                        db_column="id_partida",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_partida",
                        to="partida.partida",
                    ),
                ),
            ],
            options={
                "db_table": "Juega",
            },
        ),
    ]
