# Generated by Django 4.1.7 on 2023-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0004_partida_tiempo_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='turno_actual',
        ),
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.CharField(default='Nadie', max_length=100),
        ),
        migrations.AddField(
            model_name='partida',
            name='tematica',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
