openapi: 3.0.3
info:
  title: Trivial API
  version: 1.0.0
  description: This is the API for the Trivial project
paths:
  /api/salas/crear/:
    post:
      operationId: api_salas_crear_create
      tags:
      - SALA
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SalaCrearRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/SalaCrearRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SalaCrearRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalaCrearResponse'
          description: ''
  /api/salas/lista-jugadores-sala/:
    post:
      operationId: api_salas_lista_jugadores_sala_create
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/salas/lista-salas/:
    post:
      operationId: api_salas_lista_salas_create
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/salas/salir/:
    post:
      operationId: api_salas_salir_create
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/salas/unir/:
    post:
      operationId: api_salas_unir_create
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/usuarios/add/amigo/:
    post:
      operationId: api_usuarios_add_amigo_create
      tags:
      - USUARIO
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UsuarioAddAmigoRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioAddAmigoRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UsuarioAddAmigoRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioAddAmigoResponse'
          description: ''
  /api/usuarios/cambiar-datos/:
    post:
      operationId: api_usuarios_cambiar_datos_create
      tags:
      - USUARIO
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UsuarioCambiarDatosRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioCambiarDatosRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UsuarioCambiarDatosRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioCambiarDatosResponse'
          description: ''
  /api/usuarios/datos/:
    post:
      operationId: api_usuarios_datos_create
      tags:
      - USUARIO
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UsuarioDatosRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioDatosRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UsuarioDatosRequest'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioDatosResponse'
          description: ''
  /api/usuarios/login/:
    post:
      operationId: api_usuarios_login_create
      tags:
      - USUARIO
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UsuarioLoginRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioLoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UsuarioLoginRequest'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioLoginResponse'
          description: ''
  /api/usuarios/register/:
    post:
      operationId: api_usuarios_register_create
      tags:
      - USUARIO
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UsuarioRegistrarRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRegistrarRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UsuarioRegistrarRequest'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioRegistrarResponse'
          description: ''
  /partida/:
    post:
      operationId: partida_create
      tags:
      - partida
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    SalaCrearRequest:
      type: object
      properties:
        nombre_sala:
          type: string
        tiempo_respuesta:
          type: integer
        password_sala:
          type: string
        n_jugadores:
          type: integer
        tipo_partida:
          type: string
      required:
      - n_jugadores
      - nombre_sala
      - password_sala
      - tiempo_respuesta
      - tipo_partida
    SalaCrearResponse:
      type: object
      properties:
        OK:
          type: string
        error_nombre_sala:
          type: string
        error_tipo_sala:
          type: string
        error_tipo_partida:
          type: string
        error_n_jugadores:
          type: string
        error_tiempo_respuesta:
          type: string
      required:
      - OK
      - error_n_jugadores
      - error_nombre_sala
      - error_tiempo_respuesta
      - error_tipo_partida
      - error_tipo_sala
    UsuarioAddAmigoRequest:
      type: object
      properties:
        amigo_username:
          type: string
      required:
      - amigo_username
    UsuarioAddAmigoResponse:
      type: object
      properties:
        OK:
          type: string
        error:
          type: string
      required:
      - OK
      - error
    UsuarioCambiarDatosRequest:
      type: object
      properties:
        correo:
          type: string
          format: email
        telefono:
          type: integer
        fecha_nac:
          type: string
          format: date
      required:
      - correo
      - fecha_nac
      - telefono
    UsuarioCambiarDatosResponse:
      type: object
      properties:
        OK:
          type: string
        error_correo:
          type: string
        error_fecha_nac:
          type: string
        error_telefono:
          type: string
      required:
      - OK
      - error_correo
      - error_fecha_nac
      - error_telefono
    UsuarioDatosRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - password
      - username
    UsuarioDatosResponse:
      type: object
      properties:
        OK:
          type: string
        username:
          type: string
        correo:
          type: string
          format: email
        telefono:
          type: string
        fecha_nac:
          type: string
          format: date
        monedas:
          type: integer
        imagen:
          type: string
          format: uri
        amigos:
          type: array
          items:
            type: string
      required:
      - OK
      - amigos
      - correo
      - fecha_nac
      - imagen
      - monedas
      - telefono
      - username
    UsuarioLoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - password
      - username
    UsuarioLoginResponse:
      type: object
      properties:
        OK:
          type: string
        token:
          type: string
        error_username:
          type: string
        error_password:
          type: string
      required:
      - OK
      - error_password
      - error_username
      - token
    UsuarioRegistrarRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        confirm_password:
          type: string
        fecha_nac:
          type: string
          format: date
        correo:
          type: string
          format: email
        telefono:
          type: integer
      required:
      - confirm_password
      - correo
      - fecha_nac
      - password
      - telefono
      - username
    UsuarioRegistrarResponse:
      type: object
      properties:
        OK:
          type: string
        token:
          type: string
        error_username:
          type: string
        error_password:
          type: string
        error_confirm_password:
          type: string
        error_fecha_nac:
          type: string
        error_correo:
          type: string
        error_telefono:
          type: string
      required:
      - OK
      - error_confirm_password
      - error_correo
      - error_fecha_nac
      - error_password
      - error_telefono
      - error_username
      - token
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
