# Generated by Django 4.1.7 on 2023-04-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivial_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
