# Generated by Django 4.1.7 on 2023-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivial_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amigos",
            name="pendiente",
            field=models.BooleanField(default=True),
        ),
    ]
