# Generated by Django 4.1.7 on 2023-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivial_api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="password_sala",
            field=models.CharField(default="", max_length=200),
        ),
    ]
