# Generated by Django 4.1.7 on 2023-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivial_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image_ficha',
            field=models.CharField(default='/static/images/objetos/1.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='image_tablero',
            field=models.CharField(default='/static/images/objetos/10.png', max_length=200),
        ),
    ]
