# Generated by Django 4.1.7 on 2023-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivial_api", "0003_alter_sala_password_sala"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="tipo_partida",
            field=models.CharField(
                choices=[
                    ("Clasico", "Clasico"),
                    ("Equipo", "Equipo"),
                    ("Tematico", "Tematico"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="tipo_sala",
            field=models.CharField(
                choices=[("Publico", "Publico"), ("Privado", "Privado")], max_length=10
            ),
        ),
    ]
